CREATE DATABASE IF NOT EXISTS mysns 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE mysns;

CREATE TABLE IF NOT EXISTS user (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(32),
    password VARCHAR(32),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feed (
    no BIGINT(16) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(32),
    jsonobj VARCHAR(4096),
    INDEX idx1(id)
);

CREATE TABLE IF NOT EXISTS question (
    no BIGINT(16) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(32),
    jsonobj VARCHAR(4096),
    title VARCHAR(4086),
    INDEX idx1(id)
);